---

- name: KSCAdmin для KSC
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Добавляем KSCAdmin
    user:
      name: KSCAdmin
      password: "{{ 'Pa$$w0rd' | password_hash('sha512') }}"
      shell: /bin/bash
      createhome: no
      groups: wheel
      append: yes

  - name: Убираем запрос пароля sudo
    lineinfile:
      path: "/etc/sudoers"
      line: "KSCAdmin        ALL=(ALL)       NOPASSWD: ALL"
      insertafter: '^# %wheel.*'
      validate: /usr/sbin/visudo -cf %s

  - name: Убираем пользователя KSCAdmin с экрана входа
    lineinfile:
      path: "/etc/sddm.conf"
      line: "HideUsers=KSCAdmin"
      insertafter: '^#HideUsers='

  - name: Устанавливаем недостающие пакеты (libcrypt.so.1()(64bit))
    dnf:
      name: libxcrypt-compat
      state: latest

...